import type { ProposedCorrection, ProposedCorrectionAction, RecordRef } from './types';

// ---------------------------------------------------------------------------
// Record-impact classification (FASE 4.1 requirement 2).
//
// blast-radius.ts classifies at ASSET (table) granularity — "inventory_
// valuation requires correction". This module classifies at INDIVIDUAL
// RECORD granularity and answers a different question: "what is actually
// going to happen to record X" — so a UI or the FASE 6 remediation executor
// never has to guess whether a specific record is proof, a mutation target,
// or an unexamined ripple effect.
//
// - evidenceRecords: records that help PROVE the incident but are never
//   mutated by remediation. Sourced from the movement/journal-entry ID lists
//   that conversion-impact.ts / journal-impact.ts already identified as
//   affected-by-unit-change — never from proposedCorrections, since those
//   IDs are, by definition, the ones nothing will be written to.
// - correctionTargets: records that WILL be mutated or regenerated by
//   remediation. Sourced from proposedCorrections, deduplicated by
//   (table, recordId) and excluding actions that a correction's own
//   rollbackAssumption documents as non-mutating (RECONCILE_JOURNAL_ENTRIES
//   only confirms a cross-check; it never writes journal_entries).
// - downstreamAffectedRecords: records beyond correctionTargets that are
//   indirectly touched but not themselves corrected (e.g. a second-hop
//   report that consumes gross_margin_report). This single-hop demo
//   scenario has none today — the field and its plumbing exist so a future
//   multi-hop scenario does not require a schema change, per FASE 4.1's
//   explicit minimum-three-buckets requirement.
//
// uniqueRecordCount deduplicates a record that could otherwise appear in more
// than one bucket (not possible today since the buckets are sourced from
// disjoint ID lists, but the dedup is real, not asserted, so a future
// scenario that blurs the line is still counted correctly).
// ---------------------------------------------------------------------------

const NON_MUTATING_ACTIONS: ReadonlySet<ProposedCorrectionAction> = new Set(['RECONCILE_JOURNAL_ENTRIES']);

export interface RecordImpactInput {
  affectedMovementIds: string[];
  affectedJournalEntryIds: string[];
  proposedCorrections: ProposedCorrection[];
  downstreamAffectedRecords?: RecordRef[];
}

function recordKey(ref: RecordRef): string {
  return `${ref.table}:${ref.recordId}`;
}

function dedupeRefs(refs: RecordRef[]): RecordRef[] {
  const seen = new Map<string, RecordRef>();
  for (const ref of refs) {
    seen.set(recordKey(ref), ref);
  }
  return [...seen.values()];
}

export function buildRecordImpact(input: RecordImpactInput) {
  const evidenceRecords = dedupeRefs([
    ...input.affectedMovementIds.map((recordId) => ({ table: 'inventory_movements', recordId })),
    ...input.affectedJournalEntryIds.map((recordId) => ({ table: 'journal_entries', recordId }))
  ]);

  const correctionTargets = dedupeRefs(
    input.proposedCorrections
      .filter((c) => !NON_MUTATING_ACTIONS.has(c.action))
      .map((c) => ({ table: c.table, recordId: c.recordId }))
  );

  const downstreamAffectedRecords = dedupeRefs(input.downstreamAffectedRecords ?? []);

  const uniqueKeys = new Set([
    ...evidenceRecords.map(recordKey),
    ...correctionTargets.map(recordKey),
    ...downstreamAffectedRecords.map(recordKey)
  ]);

  return {
    evidenceRecords,
    correctionTargets,
    downstreamAffectedRecords,
    evidenceRecordCount: evidenceRecords.length,
    correctionTargetCount: correctionTargets.length,
    downstreamAffectedRecordCount: downstreamAffectedRecords.length,
    uniqueRecordCount: uniqueKeys.size
  };
}

export const ZERO_RECORD_IMPACT = {
  evidenceRecords: [],
  correctionTargets: [],
  downstreamAffectedRecords: [],
  evidenceRecordCount: 0,
  correctionTargetCount: 0,
  downstreamAffectedRecordCount: 0,
  uniqueRecordCount: 0
};
